### ISSUE TITLE
Is is possible to keep comments as-is?

### ISSUE THREAD

**Issue by daanturo** [justinbarclay/parinfer-rust-mode#104]
Sometimes I place a comment at the end of multi-line list so that adding new elements doesn't result in multiple git diff, and making line-wise operations more seamless.

Example
```
'(
  ;;
  elem1
  elem2
  ;; elem3
  ;;
  )
```

Enabling parinfer modifies it:
```
'(
  ;;
  elem1
  elem2)
  ;; elem3
  ;;
```

I haven't used parinfer before. Is this intended that I should stop relying on comments like that for the Lisp way?

Edit: it's also problematic when viewing existing packages.

**Comment by justinbarclay** [comment]
Hey @daanturo, 

`parinfer` does not support what you're asking for. In general, `parinfer` tries to enforce the standardized styles for writing lists, which is that parens are never left dangling. If you look at the demo [here](https://shaunlebron.github.io/parinfer/), under the `Comment a line` section, it behaves exactly like in parinfer-rust. 

> Edit: it's also problematic when viewing existing packages.
You should be able to use [parinfer-rust-check-before-enable](https://github.com/justinbarclay/parinfer-rust-mode/blob/c4cff069522150d2c470843bf3da1f7b7ad17bf8/parinfer-rust-mode.el#L231) to prevent editing a buffer when looking at code. If you use `defer` it will not try to edit the buffer unless you try to make a change first. If you use immediate, it will ask to change the buffer; if you decline, parinfer will disable itself.

**Comment by daanturo** [comment]
Thank you.
