### ISSUE TITLE
parinfer-rust-treat-command-as doesn't work because of this-command being nil

### ISSUE THREAD

**Issue by daanturo** [justinbarclay/parinfer-rust-mode#106]
Modifying `parinfer-rust-treat-command-as` doesn't do anything. Since in `parinfer-rust--execute`, `this-command` is always nil.

# Reproduce
1. Evaluate:
```lisp

(advice-add
 #'parinfer-rust--execute
 :around
 (lambda (func &rest args)
   (message "`this-command': %s" this-command)
   (apply func args)))

```
2. Do any editing

# Expected

Command names are reported correctly.

# Observed

`‘this-command’: nil` is repeated in the message buffer.

# Workaround

Currently if in `parinfer-rust--execute`, I change `this-command` to `last-command` it will work.

**Comment by justinbarclay** [comment]
Thanks for reporting this issue. I just spent sometime playing with this, and I was able to get `this-command` to have values in it as well. So, I don't think it is as simple as replacing the two.

I think what has changed is that `parinfer-rust--execute` is not guaranteed to act within the command loop, this would be a side-effect of changing to using the [`track-changes`](https://elpa.gnu.org/packages/track-changes.html) library.

I very rarely rely on the `treat-command-as` function. Can you add the following to your config and report back in a week or two if everything behaves as expected? If so, I'll be happy to move that into `parinfer-rust-mode`
```
(advice-add
 #'parinfer-rust--execute
 :around
 (lambda (func &rest args)
   (let ((this-command (or this-command last-command)))
     (message "`this-command': %s" this-command)
     (apply func args))))
   ```

**Comment by daanturo** [comment]
> I very rarely rely on the `treat-command-as` function. Can you add the following to your config and report back in a week or two if everything behaves as expected? If so, I'll be happy to move that into `parinfer-rust-mode`
> 
> ```
> (advice-add
>  #'parinfer-rust--execute
>  :around
>  (lambda (func &rest args)
>    (let ((this-command (or this-command
>                            last-command)))
>      (apply func args))))
> ```

I have a similar advice in my config for some days. It indeed has been working as intended.
```lisp
(defun my-parinfer-rust--execute--fix-this-command-a (func &rest args)
  (dlet ((this-command
          (or this-command
              this-original-command ; IDK, just for sure, but this is usually nil, too
              last-command)))
    (apply func args)))
```

I will report later if there's any problem.

**Comment by daanturo** [comment]
> Hey @daanturo, To follow up on last week, I'm looking to merge #107 in the next day or two unless you've had any issues with your current fix.

Thank you, I think that's fine. I haven't encountered any problems so far.
