### ISSUE TITLE
Do not change code when opening file until requested

### ISSUE THREAD

**Issue by andreyorst** [justinbarclay/parinfer-rust-mode#11]
When opening file that has incorrect formatting but balanced expressions parinfer should first check if any modifications needed, and if it is, ask user if it is okay to run paren-mode for this file to correct indentations. If user chooses `no` then parinfer should be disabled for current buffer.

This is how atom parinfer plugin works, and this is very handy when working with other people's code, that may have incorrect formatting.

Example file:

```clojure
   (defn vaiv [x]
(+ x 1))
```

**Expected behavior:**

- User opens example file above
- parinfer rust checks if any modifications will be needed
- parinfer asks `parinfer needs to modify indentation in this buffer to work. Is this OK? y/n`
  - user answers `y`
    - parinfer corrects indentation with paren mode, and runs in user-preferred mode
  - user answers `n`
    -parinfer disables itself for current buffer

The same procedure should be run when user enables parinfer for some buffer via command, so it's not a file-open hook thing.

**Actual behavior:**

File is opened with a modified state, and it's contents are:

```clojure
   (defn vaiv [x]
    (+ x 1))
```

**Comment by justinbarclay** [comment]
Yeah this a good idea, it’s something ‘parinfer-mode’ even does.

**Comment by justinbarclay** [comment]
I've pushed out a few updates tonight and this feature should be one of them :)

**Comment by andreyorst** [comment]
It works great. Thank you!
