### ISSUE TITLE
parinfer-rust-mode is on, but it is off

### ISSUE THREAD

**Issue by andreyorst** [justinbarclay/parinfer-rust-mode#19]
sometimes `parinfer-rust-mode` is enabled but no editing features are working. Disabling the mode echoes `parinfer-rust-mode disabled in current buffer` and Parinfer starts working in this buffer. Enabling mode disables parinfer. Perhaps some state is initialized wrong way? Maybe desktop mode restores some internal variables?

**Comment by justinbarclay** [comment]
There are a few things that I know could cause this: 
if parinfer-rust throws an error in a hook function, that hook function gets "unhooked". So if this happened in the `after-change-hook` or `post-command-hook`. Looking in the message buffer might give an indication if this is happening.

If it is retaining or setting state in those buffers the only thing that could in turn cause parinfer to not modify the buffer are `parinfer-rust--disable`, `undo-in-progress`, and `parinfer-rust--ignore-post-command-hook`

**Comment by andreyorst** [comment]
It seem to be Desktop save mode problem. After adding `(add-to-list 'desktop-minor-mode-table '(parinfer-rust-mode nil))` to my config the issue seemed to be fixed.
