### ISSUE TITLE
changes are ignored with 'defer policy until some event like undo

### ISSUE THREAD

**Issue by andreyorst** [justinbarclay/parinfer-rust-mode#21]
If `parinfer-rust-check-before-enable` is set to `'immediately` I can open any correct buffer, and start changing indentation. However if `parinfer-rust-check-before-enable` is set to `'defer` changes are ignored until first undo.

**Comment by justinbarclay** [comment]
Question are you using `'immediately` or `'immediate`?

There was a bug around using `'immediate` and `'defer` where parinfer-rust was only re-enabled if it detected that there were indentation issues. This should be fixed now.

**Comment by andreyorst** [comment]
My bad, I was actually using `'immediate`, but misspelled it here, because that's how it appears in the docstring:

>   "Perform check on indentation before enabling `parinfer-rust-mode'.
>
>  If Parinfer detects that it needs to change the indentation in
>  the before first running, it will prompt the user whether it is
>  OK to adjust the indentation. If the user disagrees Parinfer
>  will disable itself. The user may choose to get the prompt
>  **immediately** whenever \`parinfer-rust-mode' is enabled, defer it
>  until the first change in the buffer, or disable it and never
>  receive a prompt. When disabled, \`parinfer-rust-mode' will run
>  automatically balance the indentation for the user."

**Comment by andreyorst** [comment]
Yes, lates update fixed the issue. Thank you

**Comment by justinbarclay** [comment]
*nod* I agree the wording can be confusing. Even when I saw you originally post it I didn't notice the issue. But it has brought the issue to my attention now an I plan on putting more thought on if I want the adjective forms (`immediate`, `deferred`) or the verb/adverb forms (`immediately`, `defer`).

**Comment by andreyorst** [comment]
I think `immediate` and `deferred` is good pair
