### ISSUE TITLE
Possible incompatibility with while-no-input

### ISSUE THREAD

**Issue by andreyorst** [justinbarclay/parinfer-rust-mode#25]
Yesterday I had a pretty strange bug https://github.com/tumashu/posframe/issues/72:

>- I open lisp file with parinfer mode enabled
>- I have treemacs window on the left side of Emacs
>- I scroll upwards
>- Buffer window disappears, and treemacs window is used instead
>
>Here's a recording:  [bug.zip](https://github.com/tumashu/posframe/files/5070882/bug.zip)

@tumashu managed to fix this with this change: https://github.com/tumashu/posframe/commit/b28210748d982ca1c30debb3b3861063e7223c6c

However this means that there's a possible incompatibility between `parinfer-rust-mode` and `while-no-input`:

>while-no-input is a Lisp macro in ‘subr.el’.
>
>(while-no-input &rest BODY)
>
>  Probably introduced at or before Emacs version 22.1.
>
>Execute BODY only as long as there’s no pending input.
>If input arrives, that ends the execution of BODY,
>and ‘while-no-input’ returns t.  Quitting makes it return nil.
>If BODY finishes, ‘while-no-input’ returns whatever value BODY produced.

I think this case should also be investigated here to prevent possibility of similar bugs in the future

**Comment by justinbarclay** [comment]
Ooh that is interesting. I have no clue why this would be triggering but I will try and find some time to look into this. Thanks for the heads up.
