### ISSUE TITLE
Editing confirmation, and org-mode block auto activation

### ISSUE THREAD

**Issue by tami5** [justinbarclay/parinfer-rust-mode#26]
Hay, I'm loving the mode so far. no issue its just awesome. Thanks a lot.

I'm been wanting to disable confirmation on editing a buffer on fist visit. Its bit anoyying to be hounst. Also, I take a lot of notes on org mode and each time I add a block and try to format it, parinfer get activated even though I didn't add org to it and asks to confirm editing the block. 

A. Is there a way to make parinfer edit the buffer without asking me,
B. Disable it totally in org mode source code blocks.

Thanks

**Comment by andreyorst** [comment]
A. `(setq parinfer-rust-check-before-enable 'disabled)`
B. you can either use a hook or something like this should do the trick:
```emacs-lisp
(defun org-babel-edit-prep:emacs-lisp (&optional _babel-info)
  "Disable `parinfer-rust-mode' in Org source block for emacs-lisp."
  (parinfer-rust-mode -1))
```

**Comment by tami5** [comment]
Thanks a lot!!

**Comment by justinbarclay** [comment]
Hey I know this has been closed awhile (and thanks @andreyorst for answering this!), but I just wanted to add that you can find the list of behavior you want to customize [here](https://github.com/justinbarclay/parinfer-rust-mode#customizations) or in `M-x customize RET parinfer RET`
