### ISSUE TITLE
Melpa package?

### ISSUE THREAD

**Issue by andreyorst** [justinbarclay/parinfer-rust-mode#3]
Would be nice if we could install this via `package-install`, I think more users and testers will come to package.

**Comment by justinbarclay** [comment]
I do want to get it on to MELPA. However, there is an issue where when you undo some operations it can cause Emacs to crash. I feel that before I _really_ open this for public consumption that it should not be able to lose their data/work.

**Comment by justinbarclay** [comment]
This is next on my list to figure out, I think everything is stable enough and does the right thing in most cases, that it won't lose or change code irrevocably. Most of the bugs I'm run into now are edge cases with Emacs' commands and not within the parinfer-rust  library or the interface to library,

**Comment by andreyorst** [comment]
I also think that the package is quite stable as I never got any crash, or
corrupted any of my code

чт, 2 июл. 2020 г., 01:15 Justin <notifications@github.com>:

**Comment by justinbarclay** [comment]
It's up to the MELPA gods now.
https://github.com/melpa/melpa/pull/7003

**Comment by andreyorst** [comment]
Amazing!

сб, 4 июл. 2020 г., 21:20 Justin <notifications@github.com>:

**Comment by justinbarclay** [comment]
https://github.com/melpa/melpa/pull/7003
