### ISSUE TITLE
Tab character makes parinfer unusable

### ISSUE THREAD

**Issue by Defake** [justinbarclay/parinfer-rust-mode#32]
This is a buggy code:

```
(some-code
 	(copypasted-from-internet))
```

The second character of the second line is a tabulation. If you copy this code and paste into Emacs, parinfer will start adding spaces in front of the second line after **each** action. By action I mean moving cursor, scrolling, typing, selecting, clicking or anything you can do in an editor. Firstly I thought the plugin is completely buggy and unusable until I found the tab character.

**Comment by justinbarclay** [comment]
Thanks for bringing this issue up! Parinfer, of all variants, don't support working with tabs and unfortunately [parinfer-rust](https://github.com/eraserhd/parinfer-rust/issues/38) is no different. 

I could look at adding a some functionality to scan the buffer on initiation of parinfer-rust-mode and warn them if tab characters are detected?

**Comment by Defake** [comment]
@justinbarclay Yes, that would be perfect, thank you! When you copypaste a code from the internet, you have no idea why some of the blocks start jumping like insane if you don't know about this issue.

**Comment by justinbarclay** [comment]
I've pushed a fix that should resolve this :)

As a warning, I've chosen to only check for tabs when the buffer initially runs and not on every time parinfer executes as this could potentially be an expensive operation.
