### ISSUE TITLE
parinfer-mode smart-tab feature

### ISSUE THREAD

**Issue by FilipeJrd** [justinbarclay/parinfer-rust-mode#36]
Hello! There's any plan to add the smart-tab feature that is available on https://github.com/DogLooksGood/parinfer-mode ?

**Comment by justinbarclay** [comment]
Thanks for your interest in `parinfer-rust-mode`. Unfortunately, my intent is not to compete with `parinfer-mode` for features. Instead it's supposed to be a light wrapper around `parinfer-rust`, that for the most part, just works. 

I have done my best to engineer it such that it can work with other packages that are as concerned with brackets and whitespace as parinfer. So maybe it can work with the package that feature was based on? However, I make no guarantees that this works with other packages, parinfer is very opinionated and a pain to make it play along with other such packages.
