### ISSUE TITLE
Running parinfer-rust-mode on FreeBSD gives `void-function parinfer-rust-version`

### ISSUE THREAD

**Issue by johanthoren** [justinbarclay/parinfer-rust-mode#37]
Having set `parinfer-rust-library` to `/custom/path/to/libparinfer_rust.so` and having compiled parinfer-rust for FreeBSD and symlinking the library to the above location I get the error `void-function parinfer-rust-version` when trying to launch parinfer-rust-mode.

Is this perhaps because there is no option for `system-type 'berkeley-unix` in the function starting here:
https://github.com/justinbarclay/parinfer-rust-mode/blob/c825606e6aca4a2ed18c0af321df5f36a3c8c774/parinfer-rust-mode.el#L149

Would it be possible to take the BSD's into account? There is no pre-compiled library provided by the parinfer-rust project, but it is available as a port for FreeBSD and it's possible to compile for OpenBSD as well.

**Comment by justinbarclay** [comment]
Hmm. 
1. Does this fail when byte-compiling the library? 

or 

2. When you run `parinfer-rust-mode`? 

If it's 2 then I am not sure line 149 is involved and if it is 1 that signals a serious problem for being able to reliably customize the install path of `parinfer`.

If the error is under the seccond condition, can you confirm that your variant of Emacs has dynamic module support enabled?

If you don't know off the bat then a quick test could be: 
```
(if module-file-suffix
    (message "Emacs supports dynamic modules")
  (message "Emacs does not support dynamic modules"))
```

After you've done that can you verify that the library itself can be loaded and that it can load the rust library:
```
(require 'parinfer-rust parinfer-rust-library t)
(message (parinfer-rust-version))
```

**Comment by johanthoren** [comment]
Hi Justin,

It happens when running `parinfer-rust-mode`. I get the following when I run emacs with `--debug-init`:
```emacs-lisp
Debugger entered--Lisp error: (void-function parinfer-rust-version)
   parinfer-rust-version()
   parinfer-rust-mode(toggle)
   funcall-interactively(parinfer-rust-mode toggle)
   call-interactively(parinfer-rust-mode record nil)
   command-execute(parinfer-rust-mode record)
   counsel-M-x-action("parinfer-rust-mode")
   funcall(counsel-M-x-action "parinfer-rust-mode")
   (if ivy-marked-candidates (ivy--call-marked action) (funcall action x))
   (unwind-protect (if ivy-marked-candidates (ivy--call-marked action) (funcall action x)) (ivy-recursive-restore))
   (prog1 (unwind-protect (if ivy-marked-candidates (ivy--call-marked action) (funcall action x)) (ivy-recursive-restore)) (if (or (eq ivy-exit 'done) (minibuffer-window-active-p (selected-$
   (cond ((null action) current) (t (select-window (ivy--get-window ivy-last)) (set-buffer (progn (or (and (memq (type-of ivy-last) cl-struct-ivy-state-tags) t) (signal 'wrong-type-argument$
   (let* ((action (if (functionp ivy-inhibit-action) ivy-inhibit-action (and (not ivy-inhibit-action) (ivy--get-action ivy-last)))) (current (progn (or (and (memq (type-of ivy-last) cl-stru$
   ivy-call()
   (let* ((ivy-recursive-last (and (active-minibuffer-window) ivy-last)) (ivy--display-function (if (or ivy-recursive-last (not (window-minibuffer-p))) (progn (ivy-alist-setting ivy-display$
   (progn (let ((init-fn (ivy-alist-setting ivy-init-fns-alist caller))) (if init-fn (progn (funcall init-fn)))) (if (equal overriding-local-map '(keymap)) (progn (keyboard-quit))) (setq ca$
   (progn (let ((--cl-keys-- --cl-rest--)) (while --cl-keys-- (cond ((memq (car --cl-keys--) '(:predicate :require-match :initial-input :history :preselect :def :keymap :update-fn :sort :ac$
   (let* ((predicate (car (cdr (plist-member --cl-rest-- ':predicate)))) (require-match (car (cdr (plist-member --cl-rest-- ':require-match)))) (initial-input (car (cdr (plist-member --cl-r$
   ivy-read("M-x " ("parinfer-rust-mode" "cd" "5x5" "amx" "arp" "dbx" "dig" "erc" "ert" "eww" "ftp" "gdb" "irc" "jdb" "man" "mpc" "pdb" "pwd" "rsh" "sdb" "xdb" "calc" "diff" "dirs" "ffap" "$
   counsel-M-x()
   funcall-interactively(counsel-M-x)
   call-interactively(counsel-M-x nil nil)
   command-execute(counsel-M-x)
```

Dynamic module support is enabled.

**Comment by justinbarclay** [comment]
Ok, can you try evaluating these two lines in Emacs
```
(require 'parinfer-rust parinfer-rust-library t) ;; assuming parinfer-rust-library points to the dynamic library
(message (parinfer-rust-version))
```
It should be print out either `0.4.3` or `0.4.4-beta` to the message buffer

**Comment by johanthoren** [comment]
When evaluating the above I get: `Symbol's value as variable is void: parinfer-rust-library`. However, if I lookup the variable it is set:
```emacs-lisp
 parinfer-rust-library is a variable defined in parinfer-rust-mode.el.

 Value
 "/home/jthoren/.emacs.d/.local/etc/parinfer-rust/libparinfer_rust.so"

 Original Value
 "~/.emacs.d/.local/etc/parinfer-rust/"
```

```sh
jthoren@jt-freebsdLab:~ % ls -al .emacs.d/.local/etc/parinfer-rust/
total 8
drwxr-xr-x  2 jthoren  jthoren  512 Feb 27 23:44 .
drwxr-xr-x  5 jthoren  jthoren  512 Feb 27 23:46 ..
lrwxr-xr-x  1 jthoren  jthoren   34 Feb 27 23:44 libparinfer_rust.so -> /usr/local/lib/libparinfer_rust.so
```
Copying the library to the location instead of using a symbolic link did not change anything.

**Comment by johanthoren** [comment]
The version in FreeBSD is 0.4.3_9:
```sh
jthoren@jt-freebsdLab:~ % pkg info parinfer-rust
parinfer-rust-0.4.3_9
Name           : parinfer-rust
Version        : 0.4.3_9
Installed on   : Sat Feb 27 19:58:15 2021 CET
Origin         : editors/parinfer-rust
Architecture   : FreeBSD:12:amd64
Prefix         : /usr/local
Categories     : editors
Licenses       : ISCL
Maintainer     : mikael@FreeBSD.org
WWW            : https://github.com/eraserhd/parinfer-rust
Comment        : Infer parentheses for Clojure, Lisp, and Scheme
Annotations    :
        FreeBSD_version: 1202000
        repo_type      : binary
        repository     : FreeBSD
Flat size      : 1.18MiB
Description    :
A full-featured, super fast implementation of Shaun Lebron's parinfer.
...
```

**Comment by justinbarclay** [comment]
That is really weird, what if you expand the variable yourself?
```
(require 'parinfer-rust "/home/jthoren/.emacs.d/.local/etc/parinfer-rust/libparinfer_rust.so" t)
(message (parinfer-rust-version))
```

What I am looking to confirm or determine is that emacs _can_ load the parinfer-rust library, regardless of the config/ceremony in `parinfer-rust-mode`. If we can't get Emacs to load the library directly then I am at a loss of what `parinfer-rust-mode` can do to fix it.

**Comment by johanthoren** [comment]
I get the following:
```emacs-lisp
Debugger entered--Lisp error: (void-function parinfer-rust-version)
   (parinfer-rust-version)
   (message (parinfer-rust-version))
   (progn (require 'parinfer-rust "/home/jthoren/.emacs.d/.local/etc/parinfer-rust/li..." t) (message$
   eval((progn (require 'parinfer-rust "/home/jthoren/.emacs.d/.local/etc/parinfer-rust/li..." t) (me$
   (let ((debug-on-error t)) (eval (read (format "(progn %s)" (buffer-substring-no-properties beg end$
   (let ((result (let ((debug-on-error t)) (eval (read (format "(progn %s)" (buffer-substring-no-prop$
   (condition-case e (let ((result (let ((debug-on-error t)) (eval (read (format "(progn %s)" ...)) ($
   (string-trim-right (condition-case e (let ((result (let ((debug-on-error t)) (eval (read ...) (lis$
   (+eval-display-results (string-trim-right (condition-case e (let ((result (let (...) (eval ... ...$
   +emacs-lisp-eval(1 131)
   funcall(+emacs-lisp-eval 1 131)
   (if runner (funcall runner beg end) (let ((quickrun-option-cmdkey lang)) (quickrun-region beg end)$
   (let ((runner (or (alist-get major-mode +eval-runners) (and (require 'quickrun nil t) (equal (setq$
   (cond ((and (fboundp '+eval--ensure-in-repl-buffer) (condition-case nil (progn (get-buffer-window $
   (let ((load-file-name buffer-file-name)) (cond ((and (fboundp '+eval--ensure-in-repl-buffer) (cond$
   +eval/region(1 131)
   (if (or (assq major-mode +eval-runners) (and (fboundp '+eval--ensure-in-repl-buffer) (condition-ca$
   (let ((quickrun-option-cmdkey (and (boundp 'quickrun-option-cmdkey) quickrun-option-cmdkey))) (if $
   +eval/buffer()
   funcall-interactively(+eval/buffer)
   call-interactively(+eval/buffer)
   +eval/buffer-or-region()
   funcall-interactively(+eval/buffer-or-region)
   call-interactively(+eval/buffer-or-region nil nil)
   command-execute(+eval/buffer-or-region)
```

**Comment by justinbarclay** [comment]
I'm at a loss for the moment of what else could be wrong. I want to try to set-up a freebsd VM myself, but my time is kind of limited for that sort of thing as of late.

**Comment by johanthoren** [comment]
I've set up a VPS for troubleshooting purposes. It's running the latest FreeBSD 12.2-RELEASE. I've installed emacs and parinfer-rust. The so file has the following attributes and location: 
```bash
-rw-r--r--  1 root  wheel  628232 Feb 28 04:26 /usr/local/lib/libparinfer_rust.so
```
I intentionally didn't install any emacs configuration for you, since I assume that you would prefer to drop your own configuration on the server.

I've sent the details and credentials via email. Check your junk folder if you don't see it.

Let me know if there is anything else I can do to assist.

**Comment by justinbarclay** [comment]
Hey thanks for setting this up for me.

I was able to confirm the issue and debug it on the VM you set-up. I am not sure how they're compiling it as a package for freeBSD, but it seems like they're stripping or minimizing the information in the .so file.
![image](https://user-images.githubusercontent.com/6868388/110227640-a35f9f80-7eb7-11eb-8d59-32611112c2c7.png)

The linux version is ~3mb and the freeBSD version is 628kb (I think).

Indeed, if I run `nm /usr/local/lib/libparinfer_rust.so` it says that it can't find any symbols in the file.

So I went in and tried to set-up rust to build the package but I ran into issues with needing `libclang.so` and being unable to run `pkg install llvm60`.

So I set up my own VM of freeBSD and built `libparinfer_rust.so` and imported the library into Emacs via `(require 'parinfer-rust "./libparinfer_rust.so")` and I was able to verify libparinfer_rust could be loaded and run. 

So to me that looks like there is a problem with https://freebsd.pkgs.org/12/freebsd-aarch64/parinfer-rust-0.4.3_9.txz.html

**Comment by johanthoren** [comment]
Hi Justin,

Thanks for taking the time to look into it. I get another error when using the version cloned from the parinfer-rust git repo and building using the instructions given there:
```emacs-lisp
Debugger entered--Lisp error: (wrong-type-argument symbolp (parinfer-rust--test-p))
   boundp((parinfer-rust--test-p))
   parinfer-rust--check-version("0.4.4-beta" "0.4.3" "/home/jthoren/.emacs.d/.local/etc/parinfer-rust/li..." nil)
   parinfer-rust-mode()
   run-hooks(change-major-mode-after-body-hook prog-mode-hook emacs-lisp-mode-hook)
   apply(run-hooks (change-major-mode-after-body-hook prog-mode-hook emacs-lisp-mode-hook))
   run-mode-hooks(emacs-lisp-mode-hook)
   ...
```
Does this indicate that the version I get when compiling parinfer-rust from the git repo is incompatible with parinfer-rust-mode?

**Comment by justinbarclay** [comment]
Hmm there are minor differences between `0.4.4-beta` and `0.4.3` they both should be compatible with parinfer-rust-mode. What this looks like to me is that it's not finding `parinfer-rust--test-p` function. Which is just a function to define if `parinfer-rust-mode` is being run under a test environment.

I don't have much time to look into this today, but you could try short circuiting this call by setting parinfer-rust-version to 0.4.3 before the library is loaded
Ex:
`(const parinfer-rust-supported-version "0.4.3")`
or override the check version function. In config (ie after library is loaded but before first ran), I think:
`(defun parinfer-rust--check-version () nil)`

**Comment by johanthoren** [comment]
No difference when setting this constant to "0.4.3". I still get the same error message.

**Comment by johanthoren** [comment]
Btw, how did you build parinfer-rust on FreeBSD when you got it to work?

**Comment by justinbarclay** [comment]
I was able to dive into this more and verify that this is a `parinfer-rust--test-p` issue as a bug.

As for building parinfer-rust it went something close to:
```
pkg install rust
pkg install llvm60
git clone ...parinfer-rust...
cd ./parinfer-rust
cargo build --release parinfer-rust
```

**Comment by justinbarclay** [comment]
I _should_ have fixed the `(wrong-type-argument symbolp (parinfer-rust--test-p))` on master now.

**Comment by justinbarclay** [comment]
I'd be willing to support that if we can get that working in a Github workflow. I know Rustc/Cargo can do cross compilation, so I think this could work.

For reference you can find the Github workflow parinfer-rust-mode defaults to [here](https://github.com/justinbarclay/parinfer-rust/blob/master/.github/workflows/release.yaml).

**Comment by wahjava** [comment]
Submitted [update](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=261221) to FreeBSD port. Please post any feedback there, if you have any.

Thanks!

**Comment by justinbarclay** [comment]
Starting with v0.8.7, I have added support for downloading freebsd from my [parinfer-rust](https://github.com/justinbarclay/parinfer-rust/releases/tag/v0.4.5) fork. I have no clue if this actually works but hopefully some entrepid developers can help push it along there if it doesn't.

Also a word of warning, that starting with version 0.9 of `parinfer-rust-mode`, I will no longer support [parinfer-rust](https://github.com/eraserhd/parinfer-rust), because it's been really hard to get in [changes recently](https://github.com/justinbarclay/parinfer-rust/discussions/9)
