### ISSUE TITLE
Poor performance on big files (> 1k lines)

### ISSUE THREAD

**Issue by kisaragi-hiu** [justinbarclay/parinfer-rust-mode#38]
[My init.el](https://gitlab.com/kisaragi-hiu/.emacs.d/blob/master/.emacs.d/init.el) is 3644 lines long; with parinfer-rust-mode enabled, scrolling becomes incredibly slow. This is mainly because `parinfer-rust--execute` is hooked onto `post-command-hook`. It doesn't have to run this often.

https://github.com/DogLooksGood/parinfer-mode avoids this by having a fixed list of commands that invoke parinfer (either always immediately, or deferred on large sexps).

**Comment by justinbarclay** [comment]
I'd be happy to look at a PR for this

**Comment by PythonNut** [comment]
Perhaps [these](https://www.gnu.org/software/emacs/manual/html_node/elisp/Change-Hooks.html) would be a better fit?

**Comment by justinbarclay** [comment]
I've done some work on this. I've added an undocumented variable 
`parinfer-rust--buffer-replace-strategy` that defaults to safe. Which uses `replace-buffer-contents` to update the buffer. However, if this variable is set to fast I just do:
```
 (delete-region (point-min)
                                       (point-max))
                        (insert-buffer-substring new-buf)
```

This should fix the speed issue but may cause other issues.
What issues? I don't know just the emacs docs recommend against it 🤷
