### ISSUE TITLE
Use Paren Mode Around Yanking

### ISSUE THREAD

**Issue by justinbarclay** [justinbarclay/parinfer-rust-mode#4]
When pasting code into a lisp document, paren mode should be enabled to make sure code stays aligned regardless of the amount of whitespace in all lines.

**Comment by andreyorst** [comment]
Perhaps related to #12 ?

**Comment by justinbarclay** [comment]
I think it definitely could be. But for now it's also added as a default to the `tread-command-as` system.

This is still open because I haven't been able to test it too much lately, due to work being mostly backend. That and I knew it didn't behave the way I wanted to when yanking code because it would leave some code too indented. I've just pushed a small [patch](https://github.com/justinbarclay/parinfer-rust-mode/commit/43cde022038037d9c97d0ef0b2536defc8cdcf88#diff-d1a745a2f3d277ec4bbdfcf1670c3419R221) that also clears out any changes tracked in the buffer when the `treat-command-as` system is in effect.

**Comment by andreyorst** [comment]
Slight update.

I've been copy-pasting a bunch of code lately and everything worked fine.

**Comment by justinbarclay** [comment]
This should be working now. The yank and pop-yank commands are under the `treat-command-as` system, so parents should still be maintained. Any breakage there is more to do the the system itself and less with the command. 

Thanks to @andreyorst helping to confirm this is working I’m closing this feature request.
