### ISSUE TITLE
Possible false positive compatibility error message on Mac M1 - How to disable?

### ISSUE THREAD

**Issue by odjhey** [justinbarclay/parinfer-rust-mode#41]
I started with the auto-install `parinfer-rust` offered by this plugin. Then got an error that says
```
Module could not be opened: "/Users/user/.emacs.d/parinfer-rust/parinfer-rust-darwin.so", "dlopen(/Users/user/.emacs.d/parinfer-rust/parinfer-rust-darwin.so, 1): no suitable image found.  Did find:
	/Users/user/.emacs.d/parinfer-rust/parinfer-rust-darwin.so: mach-o, but wrong architecture
	/Users/user/.emacs.d/parinfer-rust/parinfer-rust-darwin.so: mach-o, but wrong architecture"
```

So, i went and used my built `parinfer-rust` from source, and its working, except every time I open a file, this message keeps on popping.
```
You are using a parinfer-rust library that is not compatible with this file, would you like to download the appropriate file from github?(yes or no) 
```
I can keep answering `no` and go my merry way but this message keeps popping up everytime I open a file, i'm not sure how to disable it. (If I answer yes, id go back to having no suitable image error described above)

Heres my working config.
```el
(use-package parinfer-rust-mode
   :init
   (setq parinfer-rust-library "~/.emacs.d/parinfer-rust/parinfer-rust-darwin.so")
   :hook emacs-lisp-mode)  
```
And a ref to my `parinfer-rust` build:
https://github.com/eraserhd/parinfer-rust/commit/e1eb440366211d1925bcd59561d8a1c2a75ae362

If anyone could guide me in suppressing the message, that would be great! :)

**Comment by justinbarclay** [comment]
That's currently a limitation of the package, that it only allows one version and will complain if the versions of the `parinfer-rust-mod` and `parinfer-rust` library aren't in sync. However, for... reason I am maintaining a fork of `parinfer-rust` that's on a higher version number. But the fork and the main repo are API compatible. So, I am planning on adding in support to the version checker to allow multiple compatible versions within the next couple of days.

**Comment by odjhey** [comment]
Thank you @justinbarclay, i can wait, but if you can point me to where the matching versions are maintained, that'll be great.

**Comment by justinbarclay** [comment]
Sure, thing the code that deals with version numbers is here: 
https://github.com/justinbarclay/parinfer-rust-mode/commit/41eaf5c208f6aad89d62d7a4b454ba2b65b875d1

And the version for parinfer-rust is set here:
https://github.com/eraserhd/parinfer-rust/blob/master/Cargo.toml#L3

**Comment by justinbarclay** [comment]
A [fix](https://github.com/justinbarclay/parinfer-rust-mode/pull/42) for this has been merged and it works on my machine, it should get updated on melpa sometime today. 

@odjhey If/when you test this out can you let me know if this resolves your issue?

**Comment by odjhey** [comment]
confirming it works! Thanks @justinbarclay you rock! \m/

**Comment by togakangaroo** [comment]
I am getting this now setting up a new 2021 M1 Macbook. The code seems recent, this is `parinfer-rust-mode-20210413.2`. Anyone have some suggestions?

**Comment by j-minster** [comment]
Hi, I'm also running on an M1 Mac, getting this error after compiling the library from source as per the readme: 

`File mode specification error: (module-not-gpl-compatible /Users/<redacted>/.emacs.d/parinfer-rust/libparinfer_rust.so)`

Im using parinfer-rust 0.4.3.

**Comment by togakangaroo** [comment]
I saw a similar error as well. I got it working by following [the instructions here](https://github.com/justinbarclay/parinfer-rust-mode#option-2-building-library-from-sources) to build `parinfer-rust` from source.

I then added 

    (setq parinfer-rust-library "/Users/gmauer/code/parinfer-rust/target/release/libparinfer_rust.dylib")

to my emacs initialization. Note that this is the `dylib` extension, that was built, not the `.so` extension that was downloaded.

**Comment by j-minster** [comment]
Hi George, I pointed `parinfer` to the .dylib file, in that build directory on my system, but still get the same `File mode specification error` as before. Thanks for your suggestion though.

**Comment by justinbarclay** [comment]
@togakangaroo I'm glad you were able to get it working. I haven't owned a mac for a few years, so it's hard to test these failure cases and to figure out why dylib and so are now working interchangeably.

@j-minster that is really weird that you self compiled and you're getting a not compatible error. It's essential that this  [line](
https://github.com/eraserhd/parinfer-rust/blame/b6d5d1c7562f848c3de3b0b0858cd51e138ee2b8/src/emacs_wrapper.rs#L11) exists in the version you're compiling

**Comment by justinbarclay** [comment]
@j-minster if you're using the [eraserhd/parinfer-rust](https://github.com/eraserhd/parinfer-rust) repo to compile parinfer rust, are you sure you're adding the right feature flag? `cargo build --release --features emacs`

**Comment by j-minster** [comment]
Thanks @justinbarclay, I built again using those options (the `--features emacs` bit was not in the README), but am now getting: 

`parinfer-rust-mode: Symbol’s function definition is void: parinfer-rust-version`

Thank you for replying.

**Comment by togakangaroo** [comment]
I ended up getting an M2 and had to deal with this yet again. Here are my notes on what I had to do to get it working in full
---
The core issue is this code. Note that this *shouldn't* work on an M1, the so file is for linux

#+begin_src emacs-lisp :results code
  (condition-case err
      (require 'parinfer-rust "~/.emacs.d/parinfer-rust/parinfer-rust-darwin.so" t)
    (error  err))
#+end_src

#+RESULTS:
#+begin_src emacs-lisp
(module-open-failed "/Users/georgemauer/.emacs.d/parinfer-rust/parinfer-rust-darwin.so" "dlopen(/Users/georgemauer/.emacs.d/parinfer-rust/parinfer-rust-darwin.so, 0x0001): tried: '/Users/georgemauer/.emacs.d/parinfer-rust/parinfer-rust-darwin.so' (), '/System/Volumes/Preboot/Cryptexes/OS/Users/georgemauer/.emacs.d/parinfer-rust/parinfer-rust-darwin.so' (no such file), '/Users/georgemauer/.emacs.d/parinfer-rust/parinfer-rust-darwin.so' ()")
#+end_src


Ok, so it looks like [[elisp:(progn (find-file "~/.emacs.d/parinfer-rust/parinfer-rust-darwin.so") (hexl-mode))][this file]]

 So I guess we try to recompile it or something? I've already installed [[id:5E44985D-868D-423B-AAF5-412EF0E70216][Rust]]. [[/Users/gmauer/code/parinfer-rust-mode/readme.org][I've cloned parinfer-rustmode]]

 But to build from scratch I need to go deeper into parinfer-rust itself. [[elisp:(magit-clone-regular "https://github.com/eraserhd/parinfer-rust.git" "~/code/parinfer-rust" nil)][Clone it]] to [[file:~/code/parinfer-rust][here]]

 Note that without the --features emacs parameter I get an error about dylib not being gpl compaitible

 #+begin_src emacs-lisp :results silent :dir ~/code/parinfer-rust
  (async-shell-command "cargo build --release --features emacs")
 #+end_src

So then lets move it. Note that there already was an *.so file in the destination. This is for linux. We don't need that on a Mac, we need what we built above

#+begin_src emacs-lisp :results silent
  (copy-file "~/code/parinfer-rust/target/release/libparinfer_rust.dylib" "~/.emacs.d/parinfer-rust/libparinfer_rust.dylib" 't)
#+end_src

I also need to have this run during startup to tell parinfer-rust not to use the default linux library

#+begin_src emacs-lisp
  (setq parinfer-rust-library "~/.emacs.d/parinfer-rust/libparinfer_rust.dylib")
#+end_src

This should now work
#+begin_src emacs-lisp :results code
  (condition-case err
    (require 'parinfer-rust parinfer-rust-library t)
    (error  err))
#+end_src

#+RESULTS:
#+begin_src emacs-lisp
parinfer-rust
#+end_src

Yay!
