### ISSUE TITLE
Is it possible to detect m1 macs?

### ISSUE THREAD

**Issue by justinbarclay** [justinbarclay/parinfer-rust-mode#43]
- Does Emacs have a way to determine if it is running on an m1 Mac vs Intel Mac?
 - What does rust need to target to build for m1?

**Comment by odjhey** [comment]
Haven't seen a way to do this, but heres what i got from `(describe-variable 'system-configuration)` on multiple systems

`x86_64-pc-linux-gnu`, `arm-apple-darwin20.2.0`, `x86_64-apple-darwin19.6.0`
you can prolly already guess, but this is from a linux, m1, intel mac respectively.

for target build, not familiar but you may check `aarch64-apple-darwin` and find out more about it, could be used to target arm since M1 is an arm64 with ANE

**Comment by bestlem** [comment]
However rust does run on M1 Macs

**Comment by everydayanchovies** [comment]
I built parinfer-rust-mode on an M1 and can confirm that it works.

`shell
rustc --print cfg`
```debug_assertions
target_arch="aarch64"
target_endian="little"
target_env=""
target_family="unix"
target_os="macos"
target_pointer_width="64"
target_vendor="apple"
unix
```

**Comment by martinffx** [comment]
So I had this issue with Doom, building it myself and copying it into the right spot fixed it:

```
$ git clone https://github.com/eraserhd/parinfer-rust.git
$ cargo build --release --features emacs                                                                                                                                                                                                       
   Compiling parinfer_rust v0.4.3 (/Users/martinrichards/code/opensource/parinfer-rust)
    Finished release [optimized] target(s) in 3.95s
$ cp target/release/libparinfer_rust.dylib ~/.emacs.d/.local/etc/parinfer-rust/parinfer-rust-darwin.so
```

https://github.com/justinbarclay/parinfer-rust-mode#step-1-build-the-parinfer-rust-library
https://github.com/eraserhd/parinfer-rust#stand-alone-cli

**Comment by LeonardMH** [comment]
Also using Doom Emacs here, for some reason copying the library into the `.emacs.d` directory didn't work for me, but copying it into `/usr/local/lib` did.

```
》cp target/release/libparinfer_rust.dylib /usr/local/lib/parinfer-rust-darwin.so
```

**Comment by justinbarclay** [comment]
Closing this issue as I removed support for automatically installing the intel variant for parinfer-rust and only strictly support automatically installing the arm variant.
