### ISSUE TITLE
parinfer-rust-library-directory is half-functioning

### ISSUE THREAD

**Issue by introom** [justinbarclay/parinfer-rust-mode#54]
Even with parinfer-rust-library-directory set, Emacs will **also** install parinfer-rust-darwin.so to ~/.emacs.d/ when compiling the package.

**Comment by justinbarclay** [comment]
This is byte compiling the package?

I think that means you would need to set the variable before the package is loaded or initialized.

I think the Doom Emacs package had to do something similiar

https://github.com/justinbarclay/parinfer-rust-mode/issues/35#issuecomment-780877664
