### ISSUE TITLE
Dim color for inferred parens

### ISSUE THREAD

**Issue by andreyorst** [justinbarclay/parinfer-rust-mode#6]
It would be nice if the parens that are inferred were colored differently in smart and indent modes, and keep even color in paren mode. [parinfer-mode](https://github.com/DogLooksGood/parinfer-mode) does it like [this](https://github.com/DogLooksGood/parinfer-mode/blob/eaad857ae4351f72a561ee3dec8943713510003f/parinfer-ext.el#L39). Indent mode:

![image](https://user-images.githubusercontent.com/19470159/83999892-5a041300-a96c-11ea-929b-3cd2d9842900.png)

With paren mode:

![image](https://user-images.githubusercontent.com/19470159/83999975-7bfd9580-a96c-11ea-8b53-1aa64a613af9.png)

This probably can be solved by user defined font lock rule, but would be nice to be included as an option for the package. It's a nice indication whether parens will be inferred or not.

**Comment by justinbarclay** [comment]
Thanks for you work here @andreyorst :)
