### ISSUE TITLE
Parinfer has a logo

### ISSUE THREAD

**Issue by jasonm23** [justinbarclay/parinfer-rust-mode#60]
Hi I'm working with @shaunlebron on an official logo for Parinfer and it's related projects.

https://github.com/ocodo/parinfer-logo

![](https://raw.githubusercontent.com/ocodo/parinfer-logo/master/pngs/parinfer-org-logo-128x128.png)

It's live on https://shaunlebron.github.io/parinfer/

**Comment by jasonm23** [comment]
Let me know if you have specific requirements.  There's a bunch of standard sizes, but custom sizes are available on request.

**Comment by justinbarclay** [comment]
That's cool! I have no requirements, so please open a PR with whatever you think looks good
