### ISSUE TITLE
wrong format in common-lisp when keying symbol

### ISSUE THREAD

**Issue by eric-zhu-2019** [justinbarclay/parinfer-rust-mode#61]
## case
when typing the code like:
```
(case c
  (#\; '|;|))
```
It will be formatted as:
```
(case c
  #\; '|);)
```
actually we can't enable the parienfer-mode in such file at all.

Thanks!

**Comment by justinbarclay** [comment]
I am ashamed that this stood for 5 years. But it should be fixed now, I should support common-lisp block syntax in `parinfer-rust` with [parinfer-rust-major-mode-options](https://github.com/justinbarclay/parinfer-rust-mode/blob/main/parinfer-rust-mode.el#L410).

https://github.com/justinbarclay/parinfer-rust-mode/assets/6868388/9b4c7e65-665e-47a7-979f-918fc7ac82be
