### ISSUE TITLE
Improper parens placement when a semicolon appears in a string

### ISSUE THREAD

**Issue by togakangaroo** [justinbarclay/parinfer-rust-mode#64]
Open up a scratch window, `emacs-lisp-mode`, and enable `parinfer-rust-mode` in `smart`

Input
```
(let* ((s "")))
```

Now try to put a semi-colon into that string. The second I hit the semi-colon key it becomes

```
(let* ((s ")));")))
```

If I then delete the semi-colon I get a malformed lisp file
```
(let* ((s ")))"
```

**Comment by Ludwik-Grodzki-Droit** [comment]
I'm seeing the same behaviour. To add, I'm running on a M1 Mac , under doom emacs.

**Comment by askonomm** [comment]
Yup, same here (macOS, Doom Emacs)

**Comment by justinbarclay** [comment]
I can't recreate this, but I think the root cause of this issue should be resolved as of 70927e26b7b719e32da7f9aea9bf4c94f4ea47be.

I'm happy to reopen this if others are still experiencing it.
