### ISSUE TITLE
Support string_delimiter argument to latest parinfer-rust version

### ISSUE THREAD

**Issue by garrett-hopper** [justinbarclay/parinfer-rust-mode#70]
See https://github.com/eraserhd/parinfer-rust/issues/139

`string_delimiter` argument is currently not passed which causes issues when building `parinfer-rust` from `master`

**Comment by gagbo** [comment]
The change has been merged now ( see eraserhd/parinfer-rust#133 ) but now the next step is to update the fork to this point: currently https://github.com/justinbarclay/parinfer-rust is 105 commits behind master
