### ISSUE TITLE
emacs freezes when opening a file with a large number of UTF-8 characters

### ISSUE THREAD

**Issue by ST-Saint** [justinbarclay/parinfer-rust-mode#78]
The file [agda-input.el](https://github.com/justinbarclay/parinfer-rust-mode/files/14801086/agda-input.txt)

Reproduced with `emacs -Q`

GNU Emacs 30.0.50
Development version d95f2a882d5f on master branch; build date 2024-03-15.

**Comment by justinbarclay** [comment]
Hey, thanks for reporting this.

I tried running parinfer-rust on this buffer and I was able to replicate your issue.

I've added a hidden [variable](https://github.com/justinbarclay/parinfer-rust-mode/blob/main/parinfer-rust-mode.el#L267) to do things the fast way, which improves the editing speed in `agda-input.el`. However, when running this, I noticed that parinfer-rust also freaked out on this file. I think it might be related to parinfer-rust either being confused by the formatting in that file in general or that [multi-byte chars](https://github.com/eraserhd/parinfer-rust/issues/26) sometimes cause issues.

I also pushed up a change that should prevent `parinfer-rust-mode` from completely freezing when swapping buffer contents.
