### ISSUE TITLE
Single `"` in a comment breaks formatting

### ISSUE THREAD

**Issue by narimiran** [justinbarclay/parinfer-rust-mode#99]
```clj
; regular comment

{:ab :cd}
:ef :gh
```

Pressing space on the last line correctly produces:

```clj
; regular comment

{:ab :cd
 :ef :gh}
```

----

On the other hand, if a comment contains a single `"` character:

```clj
; a comment with "

{:ab :cd}
:ef :gh
```

Pressing space on the last line doesn't move `}` to the correct place:

```clj
; a comment with "

{:ab :cd}
 :ef :gh
```

**Comment by justinbarclay** [comment]
Actually, looking into it slightly more, this is an intentional design of parinfer and, as such won't get fixed.
https://github.com/eraserhd/parinfer-rust/issues/106

**Comment by narimiran** [comment]
> Actually, looking into it slightly more, this is an intentional design of parinfer and, as such won't get fixed. [eraserhd/parinfer-rust#106](https://github.com/eraserhd/parinfer-rust/issues/106)

The link on that issue doesn't work, but I managed to find a working link: https://github.com/parinfer/parinfer.js/blob/master/doc/code.md#dangerous-quotes

I guess I'll be using the `\"` workaround.
